(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ClearAll["Global`*"];SetDirectory[NotebookDirectory[]];

<<ManipulatePrepare.m;
DrawPSPhaseDiagramcOnly[\[ScriptM]MaxPlot_,\[ScriptM]MaxMaxPlot_,\[ScriptC]MaxPlot_] := Block[{},
DrawDiagrams[\[ScriptM]MaxPlot,\[ScriptM]MaxMaxPlot,\[ScriptC]MaxPlot];
\[ScriptC]PlotDashing = restylePlot[\[ScriptC]Plot,{Dashing[Small]}];
TractableBufferStockPhaseDiag=Show[
\[ScriptC]PlotDashing
(*,Ticks->None*)
,AxesLabel->{"\!\(\*SubsuperscriptBox[\(\[ScriptM]\), \( \), \(e\)]\)","\!\(\*SubsuperscriptBox[\(\[ScriptC]\), \( \), \(e\)]\)"}
,AxesOrigin->{-Severance/\[ScriptCapitalR],0.}
,PlotRange->{{-Severance/\[ScriptCapitalR],\[ScriptM]MaxPlot},{0,\[ScriptC]MaxPlot}}]
];



