(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



SetDirectory[NotebookDirectory[]];ClearAll["Global`*"];
SetDirectory[NotebookDirectory[]];
Get["../../CoreCode/Autoload/init.m"];
Get["../../CoreCode/MakeAnalyticalResults.m"];
Get["../../CoreCode/VarsAndFuncs.m"];
Get["../../CoreCode/ParametersBase.m"];
Get["../../CoreCode/DrawDiagrams.m"];
VerboseOutput=False;FindStableArm;
{mMaxPlot,mMaxPlot}={2.5,4} \[ScriptM]E;\[ScriptC]MaxPlot=cE[mMaxPlot];
Manipulate[
Block[{$PerformanceGoal="Quality", \[GothicG]},
\[GothicG]=\[GothicG]Slider;
If[((R) \[Beta])^(1/\[Rho])/\[CapitalGamma] >=  1||((R) \[Beta])^(1/\[Rho])/(R) >=  1,Style[Text["Impatience Condition Not Satisfied."],24];Abort[]];
DrawPhaseDiagram[mMaxPlot,mMaxPlot,\[ScriptC]MaxPlot]
],{{\[GothicG]Slider,\[GothicG]Base,"\[GothicG]"},\[GothicG]Base-0.02,\[GothicG]Base+.02,0.005}]



