(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ClearAll["Global`*"];
RunningInteractively=False;(* If running from shell, process must be started from inside same directory in which notebook resides *)
If[Length[$FrontEnd] > 0,RunningInteractively=True];(* If running from the Notebook interface *)
If[RunningInteractively,NBDir=SetDirectory[NotebookDirectory[]]];
<<ManipulatePrepare.m;
FindStableArm;


(* ::Input::Initialization:: *)
Get["../../CoreCode/ParametersBase.m"];Severance=4;\[ScriptM]MaxMultiple=6;
\[GothicG]=0.00;
Get["./PikettyR-FiguresDraw.m"];
ShockWillMakeYouPayToEarnRHi=GraphicsColumn[{vEPlot,cEPlot},Frame->True,ImageSize->Large];
If[RunningInteractively,Print[ShockWillMakeYouPayToEarnRHi]];



(* ::Input::Initialization:: *)
RunningInteractively=False; Print["Warning:  It takes quite a while to generate the video animation; be patient."];If[RunningInteractively==False,
\[GothicG]List=Table[
Get["../../CoreCode/ParametersBase.m"];Severance=4;\[ScriptM]MaxMultiple=6;
\[GothicG]=\[GothicG]Loop;
Get["./PikettyR-FiguresDraw.m"];
GraphicsColumn[{vEPlot,cEPlot},PlotLabel->Column[{"","\[GothicG]="<>ToString[PaddedForm[\[GothicG],{1,4}]],"\!\(\*SuperscriptBox[\(\[ScriptB]\), \(e\)]\)="<>ToString[PaddedForm[\[ScriptB]E,{2,1}]]}],Frame->True,ImageSize->Large]
    ,{\[GothicG]Loop,\[GothicG]Base,\[GothicG]Base+0.01,0.0001}
];
(* If being viewed in the interactive Notebook interface, show the results *)
If[RunningInteractively,Print[ListAnimate[\[GothicG]List]]];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimateFirstFrame.jpg",\[GothicG]List[[1]]];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimateFirstFrame.pdf",\[GothicG]List[[1]]];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimate.swf",\[GothicG]List];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimate.flv",\[GothicG]List];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimate.mov",\[GothicG]List];
Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimate.avi",\[GothicG]List];Export["/Volumes/Data/Code/Models/Tractable/Latest/EqbmPartial/Mathematica/Examples/ManipulateParameters/PikettyR/Figures/EffectOfGrowthOnTargetListAnimate.gif",\[GothicG]List];
];

Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimateFirstFrame.jpg",\[GothicG]List[[1]]];
Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimateFirstFrame.pdf",\[GothicG]List[[1]]];
Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimate.swf",\[GothicG]List];
Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimate.flv",\[GothicG]List];
(*Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimate.mov",\[GothicG]List];*)
Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimate.avi",\[GothicG]List];Export["/Volumes/Data/Courses/Choice/Questions/BufferStock-PikettyR/LaTeX/EffectOfGrowthOnTargetListAnimate.gif",\[GothicG]List];



(* ::Input::Initialization:: *)
\[GothicG]Manipulate=
Manipulate[Block[{$PerformanceGoal="Quality", \[GothicG],\[GothicG]Base},
Get["../../CoreCode/ParametersBase.m"];Severance=4;\[ScriptM]MaxMultiple=6;
\[GothicG]=\[GothicG]Loop;
Get["./PikettyR-FiguresDraw.m"];
GraphicsColumn[{vEPlot,cEPlot},Frame->True]]
,{{\[GothicG]Loop,\[GothicG]Base,"\[GothicG]"},\[GothicG]Base,\[GothicG]Base+0.01,(*0.0002*)0.0005,Appearance->"Labeled"}
](*;
(* If being viewed in the interactive Notebook interface, show the results *)
If[RunningInteractively,Print[\[GothicG]Manipulate]];*)
